# Generated by Django 5.2.17 on 2026-09-09 08:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('placement_status', models.CharField(choices=[('UNPLACED', 'Unplaced'), ('PLACED', 'Placed'), ('OPEN_TO_INTERN', 'Open to Internships')], default='UNPLACED', max_length=20)),
                ('github_score', models.FloatField(default=0.0, help_text='Calculated score based on GitHub activity pipeline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skillsetu_student_profiles',
            },
        ),
    ]
