# Generated by Django 5.2.17 on 2026-09-09 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. IT, Mechanical, Finance', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skillsetu_industry_sectors',
            },
        ),
        migrations.CreateModel(
            name='JobBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(help_text='e.g. Backend Engineer, CAD Designer', max_length=100, unique=True)),
                ('core_skills', models.JSONField(default=list, help_text='List of mandatory core skills')),
                ('methodology_skills', models.JSONField(default=list, help_text='List of methodology/architectural practices')),
                ('tooling_skills', models.JSONField(default=list, help_text='List of tools/software utilities')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='students.industrysector')),
            ],
            options={
                'db_table': 'skillsetu_job_benchmarks',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('role_fit_matrix', models.JSONField(blank=True, default=dict)),
                ('placement_status', models.CharField(choices=[('UNPLACED', 'Unplaced'), ('PLACED', 'Placed'), ('OPEN_TO_INTERN', 'Open to Internships')], default='UNPLACED', max_length=20)),
                ('overall_confidence_score', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skillsetu_student_profiles',
            },
        ),
    ]
