# Generated by Django 5.2.17 on 2026-09-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('questions_data', models.JSONField(help_text='Stores the full generated test, correct answers, and rubrics')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='students.studentprofile')),
            ],
            options={
                'db_table': 'skillsetu_test_sessions',
            },
        ),
    ]
