# Generated by Django 5.2.17 on 2026-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_testsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_matrix',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
