# Generated by Django 5.2.17 on 2026-09-10 10:08

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentprofile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='search_corpus',
            field=models.TextField(blank=True, default=''),
        ),
    ]
