# Generated by Django 5.2.17 on 2026-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='Target job roles candidate is seeking'),
        ),
    ]
