# Generated by Django 5.2.17 on 2026-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_target_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Academic department/branch (e.g. Computer Science, Mechanical)', max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution',
            field=models.CharField(blank=True, default='', help_text='College or University name', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='raw_extracted_skills',
            field=models.JSONField(blank=True, default=list, help_text='Preserved raw resume string identifiers'),
        ),
    ]
