# Generated by Django 5.2.17 on 2026-09-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentprofile_department_studentprofile_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(blank=True, help_text='Cumulative Grade Point Average (0.0 - 10.0)', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(blank=True, default='', help_text='Academic degree e.g. B.Tech, B.S., M.S.', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Graduation Year e.g. 2026', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='LinkedIn profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', help_text='Personal portfolio or website URL', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_categorized',
            field=models.JSONField(blank=True, default=dict, help_text="Categorized skills: {'technical_skills': [], 'frameworks': [], 'tools': [], 'soft_skills': []}"),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('APPLICATION_REVIEW', 'Application Review'), ('SYSTEM', 'System Alert')], default='STATUS_CHANGE', max_length=35)),
                ('related_application_id', models.IntegerField(blank=True, null=True)),
                ('related_listing_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skillsetu_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
