# Generated by Django 5.2.17 on 2026-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_cgpa_studentprofile_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_designation',
            field=models.CharField(blank=True, default='', help_text='Current or most recent professional role (e.g. Senior Accountant, UI Designer)', max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience_years',
            field=models.FloatField(blank=True, default=0.0, help_text='Total years of work experience (0 for students/freshers)'),
        ),
    ]
