# Generated by Django 5.2.17 on 2026-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentprofile_current_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text="Industry certifications: [{'name': '...', 'issuer': '...', 'issue_year': 2024, 'credential_url': '...', 'skills_covered': []}]"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, default='', help_text='GitHub profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_strength_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Calculated profile strength score (0-100) based on 45/30/15/10 industry weighting'),
        ),
    ]
