# Generated by Django 5.2.17 on 2026-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('NEW_OPPORTUNITY', 'New Opportunity'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('APPLICATION_REVIEW', 'Application Review'), ('SYSTEM', 'System Alert')], default='STATUS_CHANGE', max_length=35),
        ),
    ]
