# Generated by Django 5.2.17 on 2026-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_records',
            field=models.JSONField(blank=True, default=list, help_text="Semester GPA records & academic transcripts: [{'semester': 1, 'sgpa': 8.8, 'credits': 24}]"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text="Hackathons, awards, honors, publications: [{'title': '...', 'issuer': '...', 'year': 2024, 'description': '...'}]"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='internships',
            field=models.JSONField(blank=True, default=list, help_text="Completed internships: [{'company': '...', 'role': '...', 'duration': '...', 'mentor_feedback': '...', 'mentor_rating': 4.5, 'certificate_url': '...'}]"),
        ),
    ]
