# Generated by Django 5.2.17 on 2026-09-10 16:24

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentprofile_academic_records_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='student_profile_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
