# Generated by Django 5.2.17 on 2026-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentprofile_student_profile_hnsw_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sponsoring_agency', models.CharField(help_text='e.g. AICTE / Ministry of Education, Amazon India, ICICI Bank', max_length=255)),
                ('domain', models.CharField(choices=[('TECH', 'Engineering & Technology'), ('FINANCE', 'Commerce & Finance'), ('MANAGEMENT', 'Management & Business'), ('DESIGN', 'Design & Creative Arts'), ('ALL', 'Cross-Domain / Universal')], default='ALL', max_length=30)),
                ('scheme_type', models.CharField(choices=[('SCHOLARSHIP', 'Scholarship & Financial Aid'), ('INTERNSHIP', 'Corporate Diversity Internship'), ('MENTORSHIP', 'Mentorship & Upskilling'), ('RESEARCH_GRANT', 'Research Grant / Fellowship'), ('INNOVATION_CHALLENGE', 'Innovation Challenge / Hackathon')], default='SCHOLARSHIP', max_length=30)),
                ('target_gender', models.CharField(choices=[('FEMALE_ONLY', 'Women / Female Candidates'), ('ALL', 'All Eligible Candidates')], default='FEMALE_ONLY', max_length=20)),
                ('benefit_summary', models.CharField(help_text='e.g. INR 50,000/year + Tuition Waiver', max_length=255)),
                ('description', models.TextField(help_text='Full program guidelines, eligibility, and deliverables')),
                ('eligible_degrees', models.JSONField(blank=True, default=list, help_text="e.g. ['B.Tech', 'BCA', 'B.Com', 'MBA', 'B.Des']")),
                ('min_cgpa', models.FloatField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('official_portal_url', models.URLField(help_text='Official portal or registration URL', max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Open for Application'), ('UPCOMING', 'Upcoming'), ('EXPIRED', 'Application Closed')], default='ACTIVE', max_length=20)),
                ('badge_color', models.CharField(default='purple', help_text='UI badge accent color', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skillsetu_government_schemes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NON_BINARY', 'Non-Binary'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', help_text='Self-identified gender for demographic opportunity matching and affirmative action schemes', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Granular feature and notification toggles: notifications, features, and privacy preferences'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('NEW_OPPORTUNITY', 'New Opportunity'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('APPLICATION_REVIEW', 'Application Review'), ('NEW_SCHEME', 'New Government / Diversity Scheme'), ('SYSTEM', 'System Alert')], default='STATUS_CHANGE', max_length=35),
        ),
    ]
