# Generated by Django 5.2.17 on 2026-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_governmentscheme_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='abc_id',
            field=models.CharField(blank=True, default='', help_text="Academic Bank of Credits account ID (e.g. 'ABC-782-901-44')", max_length=25),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='apaar_id',
            field=models.CharField(blank=True, default='', help_text="12-digit One Nation One Student ID (APAAR/ABC, e.g. '9823-4412-8901')", max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='minor_specialization',
            field=models.CharField(blank=True, default='', help_text='NEP 2020 Multidisciplinary Minor (e.g. Data Analytics, FinTech, UI/UX, Business Analysis)', max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nheqf_level',
            field=models.CharField(blank=True, choices=[('LEVEL_4_5', 'NHEQF Level 4.5: UG Certificate (Year 1 Exit)'), ('LEVEL_5_0', 'NHEQF Level 5.0: UG Diploma (Year 2 Exit)'), ('LEVEL_5_5', 'NHEQF Level 5.5: Bachelor Degree 3-Year'), ('LEVEL_6_0', 'NHEQF Level 6.0: Bachelor Degree 4-Year / Honours'), ('LEVEL_6_5', 'NHEQF Level 6.5: Post-Graduate Diploma / Honours with Research'), ('LEVEL_7_0', 'NHEQF Level 7.0: Master Degree (M.Tech, MBA, M.Com, M.Des)'), ('LEVEL_8_0', 'NHEQF Level 8.0: Doctoral / Ph.D.')], default='LEVEL_6_0', help_text='National Higher Education Qualifications Framework level', max_length=25),
        ),
    ]
