# Generated by Django 5.2.17 on 2026-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentprofile_abc_id_studentprofile_apaar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Analyzed GitHub signals: engineering_score, anti_vibe_index, CI/CD, tests, conventional commits, top repos'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of latest GitHub profile screening', null=True),
        ),
    ]
