# Generated by Django 5.2.17 on 2026-09-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_studentprofile_github_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nheqf_level',
            field=models.CharField(blank=True, choices=[('LEVEL_4_5', 'NHEQF Level 4.5: UG Certificate (Year 1 Exit)'), ('LEVEL_5_0', 'NHEQF Level 5.0: UG Diploma (Year 2 Exit)'), ('LEVEL_5_5', 'NHEQF Level 5.5: Bachelor Degree 3-Year'), ('LEVEL_6_0', 'NHEQF Level 6.0: Bachelor Degree 4-Year / Honours'), ('LEVEL_6_5', 'NHEQF Level 6.5: Post-Graduate Diploma / Honours with Research'), ('LEVEL_7_0', 'NHEQF Level 7.0: Master Degree (M.Tech, MBA, M.Com, M.Des)'), ('LEVEL_8_0', 'NHEQF Level 8.0: Doctoral / Ph.D.')], default='', help_text='National Higher Education Qualifications Framework level', max_length=25),
        ),
    ]
