"""
Django settings for skillsetu_backend project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment files (.env will not override real environment variables like on Render)
load_dotenv(BASE_DIR / '.env', override=False)

# Environment Mode Toggle (Set DEVELOPMENT=True in .env for local machine dev, False for production)
DEVELOPMENT = os.getenv('DEVELOPMENT', 'False').lower() in ('true', '1')

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-0)m*j8j!5hdlk6f^18pa*3(6zj^s0#!ubg3fp9!!o(tg_$41pr')
DEBUG = os.getenv('DEBUG', 'True' if DEVELOPMENT else 'False').lower() in ('true', '1')

_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
if '.onrender.com' not in ALLOWED_HOSTS and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.onrender.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "corsheaders",
    "ninja",

    # Our Installed Apps: 
    'accounts',
    'students',
    'recruiters',
    'institutions',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'skillsetu_backend.db_keepalive.DatabaseActivityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skillsetu_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skillsetu_backend.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# PostgreSQL Database Configuration
# - DEVELOPMENT=True  -> Uses local PostgreSQL database (DB_HOST, DB_NAME, etc.)
# - DEVELOPMENT=False -> Uses Neon Cloud PostgreSQL (DATABASE_URL)
DATABASE_URL = os.getenv('DATABASE_URL')
if not DEVELOPMENT and DATABASE_URL:
    import urllib.parse
    _db_url = urllib.parse.urlparse(DATABASE_URL)
    _query_params = urllib.parse.parse_qs(_db_url.query)
    _sslmode = _query_params.get('sslmode', [os.getenv('DB_SSLMODE', 'require')])[0]
    _is_pooler = 'pooler' in (_db_url.hostname or '')
    # For Neon PgBouncer pooler, default CONN_MAX_AGE to 0 so Django doesn't retain dead sockets
    _default_conn_age = '0' if _is_pooler else '60'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_url.path.lstrip('/'),
            'USER': urllib.parse.unquote(_db_url.username or ''),
            'PASSWORD': urllib.parse.unquote(_db_url.password or ''),
            'HOST': _db_url.hostname,
            'PORT': str(_db_url.port or '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', _default_conn_age)),
            'CONN_HEALTH_CHECKS': os.getenv('DB_CONN_HEALTH_CHECKS', 'True').lower() in ('true', '1'),
            'DISABLE_SERVER_SIDE_CURSORS': os.getenv('DB_DISABLE_SERVER_SIDE_CURSORS', 'True' if _is_pooler else 'False').lower() in ('true', '1'),
            'OPTIONS': {
                'sslmode': _sslmode,
                'connect_timeout': 10,
                'keepalives': 1,
                'keepalives_idle': 30,
                'keepalives_interval': 10,
                'keepalives_count': 5,
            },
        }
    }
else:
    _db_host = os.getenv('DB_HOST', '127.0.0.1')
    _default_ssl = 'prefer' if _db_host in ('127.0.0.1', 'localhost') else 'require'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'skillsetu_db'),
            'USER': os.getenv('DB_USER', 'skillsetu_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'skillsetu123'),
            'HOST': _db_host,
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '0')),
            'CONN_HEALTH_CHECKS': os.getenv('DB_CONN_HEALTH_CHECKS', 'True').lower() in ('true', '1'),
            'DISABLE_SERVER_SIDE_CURSORS': os.getenv('DB_DISABLE_SERVER_SIDE_CURSORS', 'False').lower() in ('true', '1'),
            'OPTIONS': {
                'sslmode': os.getenv('DB_SSLMODE', _default_ssl),
                'connect_timeout': 10,
            },
        }
    }

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'skillsetu-cache-engine',
        'TIMEOUT': int(os.getenv('CACHE_DEFAULT_TIMEOUT', '300')),
        'OPTIONS': {
            'MAX_ENTRIES': int(os.getenv('CACHE_MAX_ENTRIES', '5000'))
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Frontend Allowed Origins (Vite Server allowlist & Vercel portal)
CORS_ALLOWED_ORIGINS = [
    "https://skillsetu-portal.vercel.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
_cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_origins_env:
    for origin in _cors_origins_env.split(','):
        if origin.strip() and origin.strip() not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin.strip())

# Support dynamic Vercel preview URLs (e.g. skillsetu-portal-git-*.vercel.app)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://skillsetu-portal.vercel.app",
    "https://*.onrender.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
_csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_origins_env:
    for origin in _csrf_origins_env.split(','):
        if origin.strip() and origin.strip() not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin.strip())

# Email Delivery Configuration (Google SMTP & Fallbacks)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').replace(' ', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'Skill Setu No-Reply <noreply@skillsetu.in>')
