# Generated by Django 5.2.17 on 2026-09-10 11:28

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_studentprofile_department_studentprofile_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Corporate Identification / Tax Registration ID', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Institutional / Platform verification badge')),
                ('website', models.URLField(blank=True, max_length=500)),
                ('branding_logo_url', models.CharField(blank=True, help_text='Company logo or branding banner URL', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('headquarters', models.CharField(blank=True, help_text='City, State, Country', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='students.industrysector')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'skillsetu_companies',
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g. Lead Technical Recruiter, VP of Engineering', max_length=150)),
                ('department', models.CharField(blank=True, help_text='e.g. Talent Acquisition, Infrastructure Team', max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_company_admin', models.BooleanField(default=False, help_text='Authorizes editing company verification, website, branding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='recruiters.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skillsetu_recruiter_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Junior Backend Engineer, Robotics Intern', max_length=255)),
                ('role_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('stipend_or_ctc', models.CharField(help_text='e.g. INR 40,000/month or 12 - 16 LPA', max_length=100)),
                ('location', models.CharField(help_text='e.g. Bengaluru, Remote, Pune (Hybrid)', max_length=255)),
                ('tenure', models.CharField(blank=True, help_text='e.g. 6 Months, Permanent', max_length=100)),
                ('open_positions', models.IntegerField(default=1)),
                ('required_skills', models.JSONField(default=list, help_text="Standardized or raw skill requirements e.g. ['python', 'django', 'postgresql']")),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict, help_text="Arbitrary rules e.g. {'min_cgpa': 7.5, 'branches': ['CSE', 'IT'], 'min_confidence_score': 60}")),
                ('description', models.TextField(help_text='Detailed job description, responsibilities, and perks')),
                ('search_corpus', models.TextField(blank=True, default='')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='recruiters.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='recruiters.recruiterprofile')),
            ],
            options={
                'db_table': 'skillsetu_job_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('match_score', models.FloatField(default=0.0, help_text='Snapshot score (0.0 to 1.0) of candidate fitment at application time')),
                ('recruiter_notes', models.TextField(blank=True, help_text='Private recruiter feedback and review remarks')),
                ('status_history', models.JSONField(blank=True, default=list, help_text="Chronological audit trail: [{'status': '...', 'timestamp': '...', 'note': '...'}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='students.studentprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruiters.joblisting')),
            ],
            options={
                'db_table': 'skillsetu_job_applications',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'student')},
            },
        ),
    ]
