# Generated by Django 5.2.17 on 2026-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled interview timestamp', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Last date to submit applications', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='Flag indicating remote work option'),
        ),
    ]
