# Generated by Django 5.2.17 on 2026-09-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('recruiters', '0002_jobapplication_interview_date_and_more'),
        ('students', '0011_studentprofile_academic_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='completion_certificate_url',
            field=models.CharField(blank=True, default='', help_text='Verified credential / certificate URL', max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='internship_report_url',
            field=models.CharField(blank=True, default='', help_text='Student submitted final internship report URL', max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='internship_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='NOT_STARTED', help_text='Live lifecycle status of the internship/training', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mentor_designation',
            field=models.CharField(blank=True, default='', help_text='Mentor corporate designation', max_length=150),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mentor_feedback',
            field=models.TextField(blank=True, default='', help_text='Qualitative mentor review and evaluation remarks'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mentor_name',
            field=models.CharField(blank=True, default='', help_text='Assigned industry mentor / lead', max_length=150),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mentor_rating',
            field=models.FloatField(blank=True, help_text='Performance rating on a scale of 1.0 to 5.0', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='weekly_progress_logs',
            field=models.JSONField(blank=True, default=list, help_text="Weekly milestone updates: [{'week': 1, 'milestone': '...', 'hours': 40, 'mentor_remark': '...'}]"),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='target_audience',
            field=models.CharField(choices=[('STUDENT', 'Students & Candidates'), ('FACULTY', 'Academicians & Faculty'), ('ALL', 'Students & Faculty')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='role_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-Time Job'), ('INTERNSHIP', 'Student Internship'), ('APPRENTICESHIP', 'Apprenticeship'), ('CONTRACT', 'Contract'), ('LIVE_PROJECT', 'Live Industry Project'), ('FACULTY_INTERNSHIP', 'Faculty Internship'), ('FDP', 'Faculty Development Program (FDP)'), ('INDUSTRIAL_TRAINING', 'Industrial Training'), ('CONSULTANCY', 'Consultancy Opportunity'), ('RESEARCH_PROJECT', 'Collaborative Research Project'), ('WORKSHOP', 'Industry Workshop'), ('GUEST_LECTURE', 'Guest Lecture / Mentorship'), ('INNOVATION_CHALLENGE', 'Innovation Challenge / Hackathon')], default='FULL_TIME', max_length=30),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='stipend_or_ctc',
            field=models.CharField(help_text='e.g. INR 40,000/month, 12 - 16 LPA, or Sponsored Grant', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='tenure',
            field=models.CharField(blank=True, help_text='e.g. 6 Months, Permanent, 2 Weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(help_text='e.g. Junior Backend Engineer, Robotics Intern, EV Powertrain FDP', max_length=255),
        ),
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('TRAINING_PROGRAM', 'Industry Training Program'), ('CERTIFICATION_COURSE', 'Certification Course'), ('WORKSHOP', 'Hands-on Workshop'), ('MENTORSHIP', 'Mentorship Initiative'), ('GUEST_LECTURE', 'Executive Guest Lecture'), ('INNOVATION_CHALLENGE', 'Innovation Challenge / Hackathon')], default='WORKSHOP', max_length=30)),
                ('target_audience', models.CharField(choices=[('STUDENT', 'Students & Candidates'), ('FACULTY', 'Academicians & Faculty'), ('ALL', 'Students & Faculty')], default='ALL', max_length=20)),
                ('description', models.TextField(help_text='Detailed syllabus, prerequisites, and learning outcomes')),
                ('skills_covered', models.JSONField(default=list, help_text="e.g. ['Cloud Architecture', 'EV Powertrain', 'Financial Modeling']")),
                ('instructor_or_mentor', models.CharField(blank=True, help_text='Name & title of industry leader or mentor', max_length=200)),
                ('duration', models.CharField(help_text='e.g. 4 Weeks, 2 Days, 40 Hours', max_length=100)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline / On-Campus'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=20)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('is_certified', models.BooleanField(default=True, help_text='Awards recognized industry certificate upon completion')),
                ('branding_banner_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_programs', to='recruiters.company')),
                ('enrolled_faculty', models.ManyToManyField(blank=True, related_name='enrolled_learning_programs', to='institutions.facultyprofile')),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='enrolled_learning_programs', to='students.studentprofile')),
            ],
            options={
                'db_table': 'skillsetu_learning_programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
