# Generated by Django 5.2.17 on 2026-09-10 16:24

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_jobapplication_completion_certificate_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='joblisting',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='job_listing_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
