# Generated by Django 5.2.17 on 2026-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_joblisting_job_listing_hnsw_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='dei_initiatives',
            field=models.JSONField(blank=True, default=list, help_text="DEI perks & programs e.g. ['Women in Tech Mentorship', 'Inclusive Childcare Support', 'Equal Pay Certified']"),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_diversity_drive',
            field=models.BooleanField(default=False, help_text='Designates an affirmative action or diversity hiring initiative'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='target_gender',
            field=models.CharField(choices=[('ALL', 'All Eligible'), ('FEMALE_ONLY', 'Women Only / Female Candidates'), ('PREFER_DIVERSITY', 'Diversity Preference')], default='ALL', help_text='Target demographic for the posting', max_length=20),
        ),
    ]
