# Generated by Django 5.2.17 on 2026-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_joblisting_dei_initiatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='min_nheqf_level',
            field=models.CharField(blank=True, default='LEVEL_4_5', help_text='NEP 2020 Minimum qualification level: LEVEL_4_5 (Cert), LEVEL_5_0 (Dip), LEVEL_5_5 (3-Yr Deg), LEVEL_6_0 (4-Yr Deg)', max_length=25),
        ),
    ]
