# Generated by Django 5.2.17 on 2026-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_joblisting_min_nheqf_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Recruiter workflow, blind screening, and alert preferences'),
        ),
    ]
