# Generated by Django 5.2.17 on 2026-09-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_recruiterprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='hiring_mode',
            field=models.CharField(choices=[('COMPANY', 'Company Hiring'), ('INDIVIDUAL', 'Independent Recruiter / Self Hiring')], default='COMPANY', help_text='Designates if hiring on behalf of a company or self/independent recruiter', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Recruiter professional biography and hiring philosophy'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='experience_years',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='hiring_mode_preference',
            field=models.CharField(choices=[('COMPANY', 'Company Hiring'), ('INDIVIDUAL', 'Independent Recruiter / Self Hiring')], default='COMPANY', help_text='Default hiring attribution mode', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City, Country', max_length=255),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
