# Generated by Django 5.2.17 on 2026-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student / Candidate'), ('CANDIDATE', 'Candidate / Job Seeker'), ('RECRUITER', 'Industry Recruiter'), ('ACADEMIA', 'Academia Representative'), ('ADMIN', 'System Administrator')], default='STUDENT', help_text='Role classification to dictate portal workspace access', max_length=20),
        ),
    ]
