# Generated by Django 5.2.17 on 2026-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('LOCAL', 'Email & Password'), ('GOOGLE', 'Google OAuth2'), ('GITHUB', 'GitHub OAuth2')], default='LOCAL', help_text='Authentication identity provider', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture from OAuth provider', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, help_text='External OAuth2 subject/user ID', max_length=255, null=True),
        ),
    ]
