# Generated by Django 5.2.17 on 2026-09-10 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Computer Science & Engineering, Finance & Commerce', max_length=150)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('head_of_department', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='AISHE code or institutional code', max_length=50, null=True, unique=True)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('COLLEGE', 'Autonomous College'), ('INSTITUTE', 'National Institute / IIT / NIT / IIIT'), ('POLYTECHNIC', 'Polytechnic / Vocational Institute')], default='COLLEGE', max_length=30)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('nirf_rank', models.IntegerField(blank=True, help_text='NIRF ranking rank (if ranked)', null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('branding_logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Placement Officer', help_text='e.g. Training & Placement Officer (TPO), HOD, Dean', max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_institution_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='institutions.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='institutions.institution')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'name')},
        ),
    ]
