# Generated by Django 5.2.17 on 2026-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Institutional TPO placement alerts, curriculum radar, and DigiLocker preferences'),
        ),
    ]
